spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  messages:
    basename: messages,errors
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  profiles:
    include: secret
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  servlet:
    session:
      tracking-modes: cookie

